# Generated by Django 4.0.6 on 2022-08-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0003_alter_commune_nom_commune'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharms',
            old_name='nom',
            new_name='name',
        ),
    ]
