# Generated by Django 4.0.6 on 2022-08-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0004_rename_nom_pharms_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='nom_commune',
            field=models.CharField(choices=[('ADETIKOPE', 'ADETIKOPE'), ('LEGBASSITO', 'LEGBASSITO'), ('BAGUIDA', 'BAGUIDA'), ('BE_EST', 'BE_EST'), ('BE_CENTRE', 'BE_CENTRE'), ('BE_OUEST', 'BE_OUEST'), ('AFLAO_SAGBADO', 'AFLAO_SAGBADO'), ('AFLAO_GAKLI', 'AFLAO_GAKLI'), ('VAKPOSSITO', 'VAKPOSSITO'), ('AGOENYIVE', 'AGOENYIVE'), ('ZANGUERA', 'ZANGUERA'), ('TOGBLE', 'TOGBLE'), ('AMOUTIVE', 'AMOUTIVE')], max_length=200),
        ),
    ]
