# Generated by Django 4.0.6 on 2022-09-01 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0006_pharms_de_garde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharms_de_garde',
            name='pharm',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashbord.pharms'),
        ),
    ]
