# Generated by Django 4.0.6 on 2022-09-04 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashbord', '0007_alter_pharms_de_garde_pharm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharms_de_garde',
            name='pharm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashbord.pharms'),
        ),
    ]
